menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/Minfang-Lin
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: leavesite

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2013
